project_id = "xvuzbnqyxiuywtasimdu"

[functions.send-notification]
verify_jwt = false

[functions.invite-staff]
verify_jwt = false

[functions.reset-staff-password]
verify_jwt = false

[functions.send-client-email]
verify_jwt = false

[functions.patrol-digest]
verify_jwt = false
