import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { FileText, Download, ExternalLink } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

const ClientInvoices = () => {
  const { user } = useAuth();

  const { data: invoices = [], isLoading } = useQuery({
    queryKey: ["my-invoices", user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("invoices")
        .select("*")
        .order("created_at", { ascending: false });
      if (error) throw error;
      return data;
    },
    enabled: !!user,
  });

  const statusColor = (status: string) => {
    switch (status) {
      case "paid": return "bg-green-500/10 text-green-600 border-green-500/20";
      case "overdue": return "bg-destructive/10 text-destructive border-destructive/20";
      default: return "bg-accent/10 text-accent border-accent/20";
    }
  };

  if (isLoading) {
    return (
      <div className="space-y-3">
        {[1, 2, 3].map(i => (
          <div key={i} className="bg-background rounded-lg p-4 animate-pulse h-20" />
        ))}
      </div>
    );
  }

  if (invoices.length === 0) {
    return (
      <div className="text-center py-12">
        <FileText className="w-12 h-12 text-muted-foreground mx-auto mb-3" />
        <p className="text-muted-foreground">No invoices yet.</p>
        <p className="text-sm text-muted-foreground mt-1">Your invoices will appear here once generated by the admin.</p>
      </div>
    );
  }

  return (
    <div className="space-y-3">
      {invoices.map((inv: any) => (
        <div key={inv.id} className="bg-background rounded-lg p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div className="flex-1">
            <div className="flex items-center gap-2 flex-wrap">
              <p className="font-semibold text-sm">#{inv.invoice_number}</p>
              <Badge variant="outline" className={statusColor(inv.status)}>
                {inv.status}
              </Badge>
            </div>
            {inv.description && <p className="text-xs text-muted-foreground mt-1">{inv.description}</p>}
            <div className="flex gap-4 mt-1 text-xs text-muted-foreground">
              <span>Amount: <strong className="text-foreground">R{Number(inv.amount).toLocaleString("en-ZA", { minimumFractionDigits: 2 })}</strong></span>
              {inv.due_date && <span>Due: {new Date(inv.due_date).toLocaleDateString()}</span>}
            </div>
          </div>
          {inv.file_url && (
            <a href={inv.file_url} target="_blank" rel="noopener noreferrer">
              <Button size="sm" variant="outline">
                <Download className="w-4 h-4 mr-1" /> Download
              </Button>
            </a>
          )}
        </div>
      ))}
    </div>
  );
};

export default ClientInvoices;
